version: 2.1
jobs:
  Ankit-helloTest:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Ankit hello"
          command: "echo Hello, World from Ankit!"
workflows:
  say-hello-workflow:
    jobs:
      - Ankit-helloTest
